### ISSUE TITLE
The module raises exception and the OpenAuthLogOn form never shows up

### ISSUE THREAD

**Issue by eugenet8k** [Jetski5822/NGM.OpenAuthentication#2]
Hey guys, 

Thanks for the awesome module! I've successfully integrated it into my solution and defined couple of OpenAuth providers. Although from times to times the module fails with the exception, see below.

I use Azure hosting (where my web-server stops after some time without usage) and I couldn't figure the clear steps to reproduce yet. I could say that after module fails the default LogOn.cshtml view is shown instead of OpenAuthLogOn.cshtml one. Also every time I update the http://$$$myhost$$$/Users/Account/LogOn?ReturnUrl=%2F page the exception is being raised (I can see this in Orchard's /App_Data/Logs/ where the current stack trace is taken from) and therefore the default LogOn view is shown again in again, until the web-server is manually restarted. I thought maybe the DB connection fails for the whole site, but the rest of my views with DB connections work good, but only the OpenAuth ones throw the exceptions.

Maybe you will give me couple of the leads according to the info from stack trace:

```
2014-08-18 04:25:32,630 [93] NHibernate.Util.ADOExceptionReporter - Default - While preparing select providerco0_.Id as Id11_, providerco0_.IsEnabled as IsEnabled11_, providerco0_.DisplayName as DisplayN3_11_, providerco0_.ProviderName as Provider4_11_, providerco0_.ProviderIdKey as Provider5_11_, providerco0_.ProviderSecret as Provider6_11_, providerco0_.ProviderIdentifier as Provider7_11_ from NGM_OpenAuthentication_ProviderConfigurationRecord providerco0_ where providerco0_.ProviderName=@p0 an error occurred
 http://$$$myhost$$$/Users/Account/LogOn?ReturnUrl=%2F
2014-08-18 04:25:32,630 [93] NHibernate.Util.ADOExceptionReporter - Default - Prepare requires an open and available Connection. The connection's current state is closed.
 http://$$$myhost$$$/Users/Account/LogOn?ReturnUrl=%2F
2014-08-18 04:25:32,630 [93] Orchard.DisplayManagement.Implementation.DefaultDisplayManager - Default - ADOException thrown from Action`1 by System.Action`1[[Orchard.DisplayManagement.Implementation.ShapeDisplayingContext, Orchard.Framework, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null]]
 http://$$$myhost$$$/Users/Account/LogOn?ReturnUrl=%2F
NHibernate.ADOException: While preparing select providerco0_.Id as Id11_, providerco0_.IsEnabled as IsEnabled11_, providerco0_.DisplayName as DisplayN3_11_, providerco0_.ProviderName as Provider4_11_, providerco0_.ProviderIdKey as Provider5_11_, providerco0_.ProviderSecret as Provider6_11_, providerco0_.ProviderIdentifier as Provider7_11_ from NGM_OpenAuthentication_ProviderConfigurationRecord providerco0_ where providerco0_.ProviderName=@p0 an error occurred ---> System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.SqlAzure.ReliableSqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Hql.Ast.ANTLR.Loader.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.ExpressionQueryImpl.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Orchard.Data.Repository`1.Get(Expression`1 predicate)
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Expression`1 predicate)
   at NGM.OpenAuthentication.Services.ProviderConfigurationService.Get(String providerName)
   at NGM.OpenAuthentication.Services.OrchardOpenAuthClientProvider.GetClientData(String providerName)
   at NGM.OpenAuthentication.Shapes.<Discover>b__4(IExternalAuthenticationClient client)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NGM.OpenAuthentication.Shapes.<Discover>b__3(ShapeDisplayingContext displaying)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.<>c__DisplayClassc.<Execute>b__3(Action`1 action)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger)
```

**Comment by eugenet8k** [comment]
I asked this question on stackoverflow too http://stackoverflow.com/questions/25356621/orchards-ngm-openauthentication-sometimes-raises-exception-the-proper-logon-vi

**Comment by eugenet8k** [comment]
After some attempts to figure out the problem, I reverted the changes made in this commit https://github.com/Jetski5822/NGM.OpenAuthentication/commit/dd6eec1f90785744b526dc87aa25f6e78d1e811f, so clientsData is not calculated in OnDisplaying handler and this helped to avoid the exception in SignOn view, although the same exception now is raised sometimes (after server stopped and then started) on attempts to open Admin panel. Which is sucks, but it less sucks because at least end-users don't experience this. The stack-trace now is the following:

```
2014-08-21 06:40:34,111 [70] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
 http://$$$myhost$$$/Admin/Log
System.AggregateException: One or more errors occurred. ---> NHibernate.ADOException: While preparing select providerco0_.Id as Id11_, providerco0_.IsEnabled as IsEnabled11_, providerco0_.DisplayName as DisplayN3_11_, providerco0_.ProviderName as Provider4_11_, providerco0_.ProviderIdKey as Provider5_11_, providerco0_.ProviderSecret as Provider6_11_, providerco0_.ProviderIdentifier as Provider7_11_ from NGM_OpenAuthentication_ProviderConfigurationRecord providerco0_ where providerco0_.ProviderName=@p0 an error occurred ---> System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.SqlAzure.ReliableSqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Hql.Ast.ANTLR.Loader.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.ExpressionQueryImpl.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Orchard.Data.Repository`1.Get(Expression`1 predicate)
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Expression`1 predicate)
   at NGM.OpenAuthentication.Services.ProviderConfigurationService.Get(String providerName)
   at NGM.OpenAuthentication.Services.OrchardOpenAuthClientProvider.GetClientData(String providerName)
   at NGM.OpenAuthentication.Shapes.<Discover>b__3(IExternalAuthenticationClient client)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NGM.OpenAuthentication.Shapes.Discover(ShapeTableBuilder builder)
   at Orchard.DisplayManagement.Descriptors.DefaultShapeTableManager.<>c__DisplayClass10.<GetShapeTable>b__4(Meta`1 bindingStrategy)
   at Orchard.Caching.DefaultParallelCacheContext.<>c__DisplayClass5`2.<>c__DisplayClass7.<RunInParallel>b__1()
   at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute()
   at Orchard.Caching.DefaultParallelCacheContext.<RunInParallel>b__2[T,TResult](ITask`1 task)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<.cctor>b__0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at System.Linq.Parallel.ArrayMergeHelper`1.Execute()
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Orchard.Caching.DefaultParallelCacheContext.RunInParallel[T,TResult](IEnumerable`1 source, Func`2 selector)
   at Orchard.DisplayManagement.Descriptors.DefaultShapeTableManager.<>c__DisplayClass10.<GetShapeTable>b__3(AcquireContext`1 x)
   at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire)
   at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire)
   at Orchard.Caching.DefaultCacheManager.Get[TKey,TResult](TKey key, Func`2 acquire)
   at Orchard.DisplayManagement.Descriptors.DefaultShapeTableManager.GetShapeTable(String themeName)
   at Orchard.DisplayManagement.Descriptors.ShapeTableLocator.<>c__DisplayClass1.<Lookup>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.DisplayManagement.Descriptors.ShapeTableLocator.Lookup(String themeName)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.<>c__DisplayClass7.<FindView>b__5(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer)
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.LayoutView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
---> (Inner Exception #0) NHibernate.ADOException: While preparing select providerco0_.Id as Id11_, providerco0_.IsEnabled as IsEnabled11_, providerco0_.DisplayName as DisplayN3_11_, providerco0_.ProviderName as Provider4_11_, providerco0_.ProviderIdKey as Provider5_11_, providerco0_.ProviderSecret as Provider6_11_, providerco0_.ProviderIdentifier as Provider7_11_ from NGM_OpenAuthentication_ProviderConfigurationRecord providerco0_ where providerco0_.ProviderName=@p0 an error occurred ---> System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.SqlAzure.ReliableSqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Hql.Ast.ANTLR.Loader.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.ExpressionQueryImpl.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Orchard.Data.Repository`1.Get(Expression`1 predicate)
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Expression`1 predicate)
   at NGM.OpenAuthentication.Services.ProviderConfigurationService.Get(String providerName)
   at NGM.OpenAuthentication.Services.OrchardOpenAuthClientProvider.GetClientData(String providerName)
   at NGM.OpenAuthentication.Shapes.<Discover>b__3(IExternalAuthenticationClient client)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NGM.OpenAuthentication.Shapes.Discover(ShapeTableBuilder builder)
   at Orchard.DisplayManagement.Descriptors.DefaultShapeTableManager.<>c__DisplayClass10.<GetShapeTable>b__4(Meta`1 bindingStrategy)
   at Orchard.Caching.DefaultParallelCacheContext.<>c__DisplayClass5`2.<>c__DisplayClass7.<RunInParallel>b__1()
   at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute()
   at Orchard.Caching.DefaultParallelCacheContext.<RunInParallel>b__2[T,TResult](ITask`1 task)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<.cctor>b__0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Jetski5822** [comment]
Hi, Sorry about not getting back sooner.

Does this issue occur everytime?

I have updated to Infosets, and also pushed some caching changes. Let me know if you still get the issue.

The module has been updated to the tip of 1.x

**Comment by eugenet8k** [comment]
I started discussion on codeplex. I guess we should continue it there https://orchard.codeplex.com/discussions/566508. Thanks!

**Comment by eugenet8k** [comment]
Thanks for your updates! I will test at my environment and let you know if the exception still reproduces.

**Comment by eugenet8k** [comment]
Adding of caching (https://github.com/Jetski5822/NGM.OpenAuthentication/commit/71f7d6fb25d1e70b0ab2fbfbbd0d627f270b4d3d) helped with the exception. Please close the issue as resolved.
